// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC08QVn223g0fQUohN2L9otjMAD3Ct0Ock',
    appId: '1:1068776817423:web:611c3ff2a043d81eb6747a',
    messagingSenderId: '1068776817423',
    projectId: 'bookkikko',
    authDomain: 'bookkikko.firebaseapp.com',
    storageBucket: 'bookkikko.appspot.com',
    measurementId: 'G-T2WN4EMT8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_mubBGcitrZcP-w-cTMi6smvD7GD3O9Y',
    appId: '1:1068776817423:android:d0dd40ce43f72c40b6747a',
    messagingSenderId: '1068776817423',
    projectId: 'bookkikko',
    storageBucket: 'bookkikko.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt86d91OhujvhiQKXExLkSfPovgfZ-_aQ',
    appId: '1:1068776817423:ios:34949dd057821e7cb6747a',
    messagingSenderId: '1068776817423',
    projectId: 'bookkikko',
    storageBucket: 'bookkikko.appspot.com',
    iosClientId: '1068776817423-en9rk1nghnm360b1uhgn4puqdf3pc86q.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookkikkoBusiness',
  );
}
